// Minimal test case for nested inline module with #[path] attributes
// This mimics the structure generated by cargo-ros2-bindgen

pub mod msg {
    pub mod rmw {
        // TEST 1: Try without any directory navigation
        // Rust should look relative to where rmw "lives" (msg/)
        #[path = "bool_rmw.rs"]
        pub mod bool;

        #[path = "string_rmw.rs"]
        pub mod string;
    }

    // These should work fine - direct children of msg module
    #[path = "bool_idiomatic.rs"]
    pub mod bool;

    #[path = "string_idiomatic.rs"]
    pub mod string;
}
